/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверка, что движок запущен */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий открытый проект */
        get: operations["getProject"];
        put?: never;
        /**
         * Создать или открыть проект
         * @description `mode: open` — открыть существующую папку проекта, `mode: create` — создать новую
         *     (папка не должна существовать или должна быть пустой, родительская — существовать).
         *     Относительный `path` отсчитывается от каталога проектов движка (`--workspace`), абсолютный — как есть;
         *     `..` в пути — `400`. Предыдущий проект закрывается; пока идут задачи — `409`.
         */
        post: operations["openProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Записи проекта */
        get: operations["listSources"];
        put?: never;
        /**
         * Импортировать запись (задача)
         * @description Принимает либо JSON `{path}` (путь к файлу на диске — CLI, десктоп, Docker с `./workspace`),
         *     либо `multipart/form-data` с полем `file` (браузер). В обоих случаях файл копируется
         *     в `sources/<sha256>.<ext>` проекта. Читаются только обычные файлы. Импорт возвращает задачу:
         *     прогресс — `GET /api/jobs/{id}/events`, соединения появляются в списке по мере импорта.
         *     Повторный импорт того же файла — новый импорт, не склейка.
         */
        post: operations["importSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{sha256}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Диагностика записи
         * @description Что не удалось или не поддерживается в записи; остальные кадры при этом обработаны.
         */
        get: operations["getSourceDiagnostics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * TCP-соединения
         * @description Порядок — по первому кадру, стабильный. Во время импорта список растёт: `total` — число уже
         *     известных соединений.
         */
        get: operations["listConnections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams/{stream}/bytes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Байты направленного потока и карта сегментов
         * @description Диапазон `[from, from+len)` потока. Ответ — список участков карты, обрезанных по диапазону:
         *     `data` — байты есть (base64), `gap` — данных нет в записи (байтов нет, нули не подставляются),
         *     `ambiguous` — перекрытие с разными байтами (`data` — вариант по политике проекта,
         *     `variants` — все варианты). Диапазон за концом потока усекается, `length` в ответе — фактическая
         *     длина. Максимум `len` — 1 МиБ, больше — `400`.
         */
        get: operations["getStreamBytes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frames/{source}/{frameNo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Кадр записи
         * @description Номера кадров — с 1, как в Wireshark. Ответ содержит байты кадра целиком, разобранные заголовки
         *     и, если payload попал в поток, ссылку на участок потока (переход «кадр → байты»).
         */
        get: operations["getFrame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Задачи текущей сессии */
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Состояние задачи */
        get: operations["getJob"];
        put?: never;
        post?: never;
        /**
         * Отменить задачу
         * @description Запрос отмены; задача останавливается на ближайшей проверке токена отмены и переходит в `cancelled`.
         *     Уже завершённая задача — `409`. Частичные результаты отменённого импорта удаляются.
         */
        delete: operations["cancelJob"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Прогресс задачи (SSE)
         * @description `text/event-stream`. Первым событием приходит текущее состояние. События: `progress`
         *     (данные — `{jobId, stage, done, total, unit}`), `state` (данные — `Job`, при смене состояния),
         *     поток закрывается после терминального состояния. Для завершённой задачи — одно событие `state`
         *     и закрытие. Заголовок токена в `EventSource` не передать, поэтому клиент использует
         *     `fetch` со стримом.
         */
        get: operations["streamJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description sha256 содержимого, строчные hex-цифры
         * @example 3f5a1c0d9e8b7a6f5e4d3c2b1a09f8e7d6c5b4a39281706f5e4d3c2b1a0f9e8d
         */
        Sha256: string;
        /** @description RFC 9457 Problem Details */
        Problem: {
            /** @description Идентификатор вида ошибки, `urn:protoledger:problem:<код>` */
            type: string;
            /** @description Краткое название по-русски */
            title: string;
            status: number;
            /** @description Что произошло и что делать, по-русски */
            detail?: string;
            /** @description Только для превышения предела */
            limit?: {
                /** @description Имя предела из docs/limits.md */
                name: string;
                value: number;
                unit: string;
            };
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            version: string;
        };
        /** @description Настройки сборки потоков; часть воспроизводимости проекта */
        ProjectSettings: {
            /**
             * @description Какие байты брать при перекрытии с различающимся содержимым
             * @enum {string}
             */
            overlapPolicy: "first" | "last" | "flag";
            /**
             * @description Что делать с кадрами с неверной контрольной суммой TCP
             * @enum {string}
             */
            checksumPolicy: "ignore" | "warn" | "drop";
        };
        Project: {
            name: string;
            /** @description Путь к папке проекта */
            path: string;
            formatVersion: number;
            engineVersion: string;
            settings: components["schemas"]["ProjectSettings"];
            sourceCount: number;
        };
        OpenProjectRequest: {
            /** @description Путь к папке проекта */
            path: string;
            /** @enum {string} */
            mode: "open" | "create";
        };
        ImportByPathRequest: {
            /** @description Путь к файлу записи на диске */
            path: string;
        };
        /**
         * @description `importing` — идёт импорт, `ready` — готова, `error` — файл не принят или разобран с ошибкой,
         *     `damaged` — копия в проекте изменена или пропала (sha256 не совпал).
         * @enum {string}
         */
        SourceStatus: "importing" | "ready" | "error" | "damaged";
        Source: {
            sha256: components["schemas"]["Sha256"];
            /**
             * @description Последний импорт этой записи, `imp-0001`…
             * @example imp-0001
             */
            importId: string;
            /** @description Исходное имя файла */
            name: string;
            /** @enum {string} */
            format: "pcap" | "pcapng";
            sizeBytes: number;
            status: components["schemas"]["SourceStatus"];
            frameCount: number;
            connectionCount: number;
        };
        SourcePage: {
            items: components["schemas"]["Source"][];
            total: number;
            limit: number;
            offset: number;
        };
        /** @enum {string} */
        Severity: "info" | "warning" | "error";
        /** @description Группа однотипных замечаний к записи; ограничение реализации или дефект данных, не вывод о протоколе */
        Diagnostic: {
            /**
             * @description Стабильный код: `unsupported_link_type`, `non_ip`, `ipv6_skipped`, `non_tcp`, `ip_fragment`,
             *     `truncated_frame`, `bad_ip_header`, `bad_tcp_header`, `bad_checksum`, `bad_block`, `limit_exceeded`
             */
            code: string;
            severity: components["schemas"]["Severity"];
            title: string;
            detail: string;
            /** @description Сколько кадров затронуто */
            count: number;
            /** @description Первые номера затронутых кадров */
            frameNumbers: number[];
        };
        SourceDiagnostics: {
            sha256: components["schemas"]["Sha256"];
            frames: {
                total: number;
                parsed: number;
                skipped: number;
            };
            items: components["schemas"]["Diagnostic"][];
        };
        Endpoint: {
            /** @description Адрес IPv4 */
            address: string;
            port: number;
        };
        /**
         * @description Признаки для значков в списке: повторы сегментов, дыры, неоднозначные перекрытия,
         *     нет SYN (роли неизвестны), неверные контрольные суммы, усечённые кадры,
         *     порты переиспользованы раньше (соединение начато заново).
         * @enum {string}
         */
        ConnectionFlag: "retransmissions" | "gaps" | "ambiguous" | "no_syn" | "bad_checksum" | "truncated" | "reused_ports";
        /**
         * @description `a` — инициатор, если виден SYN; иначе меньший адрес:порт
         * @enum {string}
         */
        DirectionKind: "a_to_b" | "b_to_a";
        StreamSummary: {
            /** @description `<соединение>:ab` или `<соединение>:ba` */
            id: string;
            direction: components["schemas"]["DirectionKind"];
            /** @description Длина потока, байт: data + gap + ambiguous */
            length: number;
            dataBytes: number;
            gapBytes: number;
            ambiguousBytes: number;
            /** @description Начало потока известно (виден SYN); иначе смещение 0 — первый наблюдённый байт */
            startAvailable: boolean;
        };
        Connection: {
            /**
             * @description Идентификатор `<первые 8 hex sha256>:c0001`
             * @example 3f5a1c0d:c0001
             */
            id: string;
            source: components["schemas"]["Sha256"];
            a: components["schemas"]["Endpoint"];
            b: components["schemas"]["Endpoint"];
            /** @description Роли клиент/сервер установлены по SYN */
            rolesKnown: boolean;
            /**
             * Format: date-time
             * @description Время захвата первого кадра
             */
            firstFrameTime: string;
            /**
             * Format: date-time
             * @description Время захвата последнего кадра
             */
            lastFrameTime: string;
            frameCount: number;
            /**
             * @description Как закрыто соединение; `open` — конец записи раньше закрытия
             * @enum {string}
             */
            close: "fin" | "rst" | "open";
            flags: components["schemas"]["ConnectionFlag"][];
            /** @description Два направленных потока */
            streams: components["schemas"]["StreamSummary"][];
        };
        ConnectionPage: {
            items: components["schemas"]["Connection"][];
            total: number;
            limit: number;
            offset: number;
        };
        FrameRef: {
            source: components["schemas"]["Sha256"];
            frameNo: number;
            /** @description Кадр — повтор уже принятых байтов (ретрансмиссия) */
            duplicate: boolean;
        };
        /** @enum {string} */
        SegmentStatus: "data" | "gap" | "ambiguous";
        SegmentVariant: {
            data: string;
            frames: components["schemas"]["FrameRef"][];
        };
        /** @description Участок карты потока `[start, end)`, обрезанный по запрошенному диапазону */
        Segment: {
            start: number;
            end: number;
            status: components["schemas"]["SegmentStatus"];
            /** @description Байты участка в base64; `null` для `gap` */
            data: string | null;
            /** @description Кадры-источники, включая повторы; для `gap` пусто */
            frames: components["schemas"]["FrameRef"][];
            /** @description Только для `ambiguous` — все варианты байтов с кадрами; `data` — выбранный политикой проекта */
            variants?: components["schemas"]["SegmentVariant"][];
        };
        StreamBytes: {
            stream: string;
            from: number;
            /** @description Фактическая длина диапазона после усечения по концу потока */
            length: number;
            streamLength: number;
            /** @description Участки подряд, без пропусков, покрывают `[from, from+length)` */
            segments: components["schemas"]["Segment"][];
        };
        Ethernet: {
            src: string;
            dst: string;
            etherType: number;
        };
        Ipv4: {
            src: string;
            dst: string;
            ttl: number;
            protocol: number;
            headerLength: number;
        };
        Tcp: {
            srcPort: number;
            dstPort: number;
            seq: number;
            ack: number;
            flags: ("fin" | "syn" | "rst" | "psh" | "ack" | "urg" | "ece" | "cwr")[];
            window: number;
            headerLength: number;
            /**
             * @description `unknown` — кадр усечён, сумму проверить нельзя
             * @enum {string}
             */
            checksum: "ok" | "bad" | "unknown";
        };
        /** @description Куда попали байты payload кадра */
        StreamRange: {
            stream: string;
            start: number;
            end: number;
            duplicate: boolean;
        };
        Frame: {
            source: components["schemas"]["Sha256"];
            frameNo: number;
            /**
             * Format: date-time
             * @description Время захвата из записи
             */
            time: string;
            /** @description Смещение кадра в файле записи */
            fileOffset: number;
            capturedLength: number;
            /** @description Длина на проводе; больше captured — кадр усечён */
            originalLength: number;
            /** @description Байты кадра целиком */
            data: string;
            ethernet?: components["schemas"]["Ethernet"] | null;
            ipv4?: components["schemas"]["Ipv4"] | null;
            tcp?: components["schemas"]["Tcp"] | null;
            payload?: {
                /** @description Смещение payload внутри кадра */
                offset: number;
                length: number;
            } | null;
            streamRange?: components["schemas"]["StreamRange"] | null;
            /** @description Замечания к этому кадру */
            diagnostics: {
                code: string;
                severity: components["schemas"]["Severity"];
                title: string;
            }[];
        };
        /** @enum {string} */
        JobKind: "import";
        /** @enum {string} */
        JobState: "queued" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled";
        JobProgress: {
            /** @enum {string} */
            stage: "reading" | "reassembling" | "saving" | "done";
            done: number;
            /** @description 0, если ещё неизвестно */
            total: number;
            /** @enum {string} */
            unit: "frames" | "bytes";
        };
        ImportResult: {
            sourceSha256: components["schemas"]["Sha256"];
            importId: string;
        };
        Job: {
            /** @example job-0001 */
            id: string;
            kind: components["schemas"]["JobKind"];
            state: components["schemas"]["JobState"];
            progress: components["schemas"]["JobProgress"];
            /** @description Только для `succeeded` */
            result?: components["schemas"]["ImportResult"] | null;
            /** @description Только для `failed` */
            error?: components["schemas"]["Problem"] | null;
        };
        JobAccepted: {
            /** @example job-0001 */
            jobId: string;
        };
    };
    responses: {
        /** @description Некорректный запрос (параметры, тело, путь вне допустимого) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:protoledger:problem:bad-request",
                 *       "title": "Некорректный запрос",
                 *       "status": 400,
                 *       "detail": "Параметр len должен быть от 1 до 1048576."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Нет или неверный токен сессии */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:protoledger:problem:unauthorized",
                 *       "title": "Нет доступа",
                 *       "status": 401,
                 *       "detail": "Не передан или неверен заголовок X-Protoledger-Token."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Чужой Host или Origin */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:protoledger:problem:forbidden",
                 *       "title": "Запрос отклонён",
                 *       "status": 403,
                 *       "detail": "Заголовок Host не совпадает с адресом движка."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Объект не найден */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:protoledger:problem:not-found",
                 *       "title": "Не найдено",
                 *       "status": 404,
                 *       "detail": "Поток 3f5a1c0d:c0009:ab не существует."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Проект не открыт */
        NoProject: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:protoledger:problem:no-project",
                 *       "title": "Проект не открыт",
                 *       "status": 409,
                 *       "detail": "Сначала создайте или откройте проект (POST /api/project)."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Конфликт состояния (задача уже завершена, у проекта идут задачи) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:protoledger:problem:conflict",
                 *       "title": "Конфликт состояния",
                 *       "status": 409,
                 *       "detail": "Задача job-0001 уже завершена."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Тело запроса или файл больше защитного предела */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:protoledger:problem:limit-exceeded",
                 *       "title": "Превышен предел",
                 *       "status": 413,
                 *       "detail": "Размер файла 2 ГиБ больше предела 1 ГиБ.",
                 *       "limit": {
                 *         "name": "max_source_size",
                 *         "value": 1073741824,
                 *         "unit": "bytes"
                 *       }
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Недопустимый тип содержимого запроса */
        UnsupportedMedia: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:protoledger:problem:unsupported-media",
                 *       "title": "Неподдерживаемый тип",
                 *       "status": 415,
                 *       "detail": "Ожидается application/json или multipart/form-data."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Запрос разобран, но объект не принят (не проект, не запись, формат не поддерживается) */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:protoledger:problem:unprocessable",
                 *       "title": "Файл не принят",
                 *       "status": 422,
                 *       "detail": "Файл не похож на PCAP или PCAPNG."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Достигнут предел одновременных долгих задач */
        TooManyJobs: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:protoledger:problem:too-many-jobs",
                 *       "title": "Слишком много задач",
                 *       "status": 429,
                 *       "detail": "Одновременно можно выполнять не больше 2 задач, дождитесь завершения.",
                 *       "limit": {
                 *         "name": "max_concurrent_jobs",
                 *         "value": 2,
                 *         "unit": "jobs"
                 *       }
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Размер страницы */
        Limit: number;
        /** @description Сколько элементов пропустить */
        Offset: number;
        /** @description sha256 записи */
        SourceSha: components["schemas"]["Sha256"];
        /** @description Идентификатор задачи */
        JobId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Движок работает */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "version": "0.1.0"
                     *     }
                     */
                    "application/json": components["schemas"]["Health"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Проект открыт */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "name": "demo",
                     *       "path": "/workspace/demo.protoledger",
                     *       "formatVersion": 1,
                     *       "engineVersion": "0.1.0",
                     *       "settings": {
                     *         "overlapPolicy": "first",
                     *         "checksumPolicy": "warn"
                     *       },
                     *       "sourceCount": 2
                     *     }
                     */
                    "application/json": components["schemas"]["Project"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["NoProject"];
        };
    };
    openProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "path": "/workspace/demo.protoledger",
                 *       "mode": "create"
                 *     }
                 */
                "application/json": components["schemas"]["OpenProjectRequest"];
            };
        };
        responses: {
            /** @description Проект открыт или создан */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "name": "demo",
                     *       "path": "/workspace/demo.protoledger",
                     *       "formatVersion": 1,
                     *       "engineVersion": "0.1.0",
                     *       "settings": {
                     *         "overlapPolicy": "first",
                     *         "checksumPolicy": "warn"
                     *       },
                     *       "sourceCount": 0
                     *     }
                     */
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
            422: components["responses"]["Unprocessable"];
        };
    };
    listSources: {
        parameters: {
            query?: {
                /** @description Размер страницы */
                limit?: components["parameters"]["Limit"];
                /** @description Сколько элементов пропустить */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница записей, в порядке импорта */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "sha256": "3f5a1c0d9e8b7a6f5e4d3c2b1a09f8e7d6c5b4a39281706f5e4d3c2b1a0f9e8d",
                     *           "importId": "imp-0001",
                     *           "name": "session-1.pcapng",
                     *           "format": "pcapng",
                     *           "sizeBytes": 482113,
                     *           "status": "ready",
                     *           "frameCount": 1203,
                     *           "connectionCount": 4
                     *         }
                     *       ],
                     *       "total": 1,
                     *       "limit": 50,
                     *       "offset": 0
                     *     }
                     */
                    "application/json": components["schemas"]["SourcePage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["NoProject"];
        };
    };
    importSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "path": "/workspace/captures/session-1.pcapng"
                 *     }
                 */
                "application/json": components["schemas"]["ImportByPathRequest"];
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Файл PCAP или PCAPNG
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Импорт принят, создана задача */
            202: {
                headers: {
                    /** @description Адрес задачи */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "jobId": "job-0001"
                     *     }
                     */
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["NoProject"];
            413: components["responses"]["TooLarge"];
            415: components["responses"]["UnsupportedMedia"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["TooManyJobs"];
        };
    };
    getSourceDiagnostics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description sha256 записи */
                sha256: components["parameters"]["SourceSha"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Диагностика записи */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "sha256": "3f5a1c0d9e8b7a6f5e4d3c2b1a09f8e7d6c5b4a39281706f5e4d3c2b1a0f9e8d",
                     *       "frames": {
                     *         "total": 1203,
                     *         "parsed": 1190,
                     *         "skipped": 13
                     *       },
                     *       "items": [
                     *         {
                     *           "code": "ipv6_skipped",
                     *           "severity": "info",
                     *           "title": "Кадры IPv6 пропущены",
                     *           "detail": "IPv6 не поддерживается, кадры не разобраны.",
                     *           "count": 11,
                     *           "frameNumbers": [
                     *             14,
                     *             15,
                     *             90
                     *           ]
                     *         },
                     *         {
                     *           "code": "bad_checksum",
                     *           "severity": "warning",
                     *           "title": "Неверная контрольная сумма TCP",
                     *           "detail": "Все неверные суммы — от одного хоста, вероятно offloading на стороне отправителя.",
                     *           "count": 2,
                     *           "frameNumbers": [
                     *             201,
                     *             202
                     *           ]
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["SourceDiagnostics"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["NoProject"];
        };
    };
    listConnections: {
        parameters: {
            query?: {
                /** @description Размер страницы */
                limit?: components["parameters"]["Limit"];
                /** @description Сколько элементов пропустить */
                offset?: components["parameters"]["Offset"];
                /** @description Только соединения этой записи (sha256) */
                source?: components["schemas"]["Sha256"];
                /** @description Порт любой из сторон */
                port?: number;
                /** @description Адрес любой из сторон (точное совпадение) */
                address?: string;
                /** @description Только соединения с этим признаком */
                flag?: components["schemas"]["ConnectionFlag"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница соединений */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": "3f5a1c0d:c0001",
                     *           "source": "3f5a1c0d9e8b7a6f5e4d3c2b1a09f8e7d6c5b4a39281706f5e4d3c2b1a0f9e8d",
                     *           "a": {
                     *             "address": "192.168.1.10",
                     *             "port": 51234
                     *           },
                     *           "b": {
                     *             "address": "192.168.1.20",
                     *             "port": 9000
                     *           },
                     *           "rolesKnown": true,
                     *           "firstFrameTime": "2026-10-09T12:00:00.100000000Z",
                     *           "lastFrameTime": "2026-10-09T12:00:05.420000000Z",
                     *           "frameCount": 42,
                     *           "close": "fin",
                     *           "flags": [
                     *             "retransmissions"
                     *           ],
                     *           "streams": [
                     *             {
                     *               "id": "3f5a1c0d:c0001:ab",
                     *               "direction": "a_to_b",
                     *               "length": 310,
                     *               "dataBytes": 310,
                     *               "gapBytes": 0,
                     *               "ambiguousBytes": 0,
                     *               "startAvailable": true
                     *             },
                     *             {
                     *               "id": "3f5a1c0d:c0001:ba",
                     *               "direction": "b_to_a",
                     *               "length": 1480,
                     *               "dataBytes": 1400,
                     *               "gapBytes": 80,
                     *               "ambiguousBytes": 0,
                     *               "startAvailable": true
                     *             }
                     *           ]
                     *         }
                     *       ],
                     *       "total": 1,
                     *       "limit": 50,
                     *       "offset": 0
                     *     }
                     */
                    "application/json": components["schemas"]["ConnectionPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["NoProject"];
        };
    };
    getStreamBytes: {
        parameters: {
            query?: {
                /** @description Смещение начала диапазона */
                from?: number;
                /** @description Длина диапазона в байтах */
                len?: number;
            };
            header?: never;
            path: {
                /** @description Идентификатор направленного потока */
                stream: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Байты и карта сегментов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "stream": "3f5a1c0d:c0001:ba",
                     *       "from": 0,
                     *       "length": 24,
                     *       "streamLength": 1480,
                     *       "segments": [
                     *         {
                     *           "start": 0,
                     *           "end": 16,
                     *           "status": "data",
                     *           "data": "qlUAEAABAAAAAAAIAAAAAA==",
                     *           "frames": [
                     *             {
                     *               "source": "3f5a1c0d9e8b7a6f5e4d3c2b1a09f8e7d6c5b4a39281706f5e4d3c2b1a0f9e8d",
                     *               "frameNo": 7,
                     *               "duplicate": false
                     *             }
                     *           ]
                     *         },
                     *         {
                     *           "start": 16,
                     *           "end": 24,
                     *           "status": "gap",
                     *           "data": null,
                     *           "frames": []
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["StreamBytes"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["NoProject"];
        };
    };
    getFrame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description sha256 записи */
                source: components["schemas"]["Sha256"];
                frameNo: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Кадр */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "source": "3f5a1c0d9e8b7a6f5e4d3c2b1a09f8e7d6c5b4a39281706f5e4d3c2b1a0f9e8d",
                     *       "frameNo": 7,
                     *       "time": "2026-10-09T12:00:00.250000000Z",
                     *       "fileOffset": 1024,
                     *       "capturedLength": 70,
                     *       "originalLength": 70,
                     *       "data": "AAECAwQFBgcICQoLDA0ODw==",
                     *       "ethernet": {
                     *         "src": "00:11:22:33:44:55",
                     *         "dst": "66:77:88:99:aa:bb",
                     *         "etherType": 2048
                     *       },
                     *       "ipv4": {
                     *         "src": "192.168.1.20",
                     *         "dst": "192.168.1.10",
                     *         "ttl": 64,
                     *         "protocol": 6,
                     *         "headerLength": 20
                     *       },
                     *       "tcp": {
                     *         "srcPort": 9000,
                     *         "dstPort": 51234,
                     *         "seq": 1000,
                     *         "ack": 311,
                     *         "flags": [
                     *           "ack",
                     *           "psh"
                     *         ],
                     *         "window": 502,
                     *         "headerLength": 32,
                     *         "checksum": "ok"
                     *       },
                     *       "payload": {
                     *         "offset": 66,
                     *         "length": 4
                     *       },
                     *       "streamRange": {
                     *         "stream": "3f5a1c0d:c0001:ba",
                     *         "start": 0,
                     *         "end": 4,
                     *         "duplicate": false
                     *       },
                     *       "diagnostics": []
                     *     }
                     */
                    "application/json": components["schemas"]["Frame"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["NoProject"];
        };
    };
    listJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Задачи, новые первыми */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": "job-0001",
                     *           "kind": "import",
                     *           "state": "running",
                     *           "progress": {
                     *             "stage": "reassembling",
                     *             "done": 600,
                     *             "total": 1203,
                     *             "unit": "frames"
                     *           }
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        items: components["schemas"]["Job"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор задачи */
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Задача */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "job-0001",
                     *       "kind": "import",
                     *       "state": "succeeded",
                     *       "progress": {
                     *         "stage": "done",
                     *         "done": 1203,
                     *         "total": 1203,
                     *         "unit": "frames"
                     *       },
                     *       "result": {
                     *         "sourceSha256": "3f5a1c0d9e8b7a6f5e4d3c2b1a09f8e7d6c5b4a39281706f5e4d3c2b1a0f9e8d",
                     *         "importId": "imp-0001"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор задачи */
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Отмена запрошена */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "job-0001",
                     *       "kind": "import",
                     *       "state": "cancelling",
                     *       "progress": {
                     *         "stage": "reassembling",
                     *         "done": 600,
                     *         "total": 1203,
                     *         "unit": "frames"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    streamJobEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор задачи */
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Поток событий */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example event: progress
                     *     data: {"jobId":"job-0001","stage":"reassembling","done":600,"total":1203,"unit":"frames"}
                     *
                     *     event: state
                     *     data: {"id":"job-0001","kind":"import","state":"succeeded","progress":{"stage":"done","done":1203,"total":1203,"unit":"frames"},"result":{"sourceSha256":"3f5a1c0d9e8b7a6f5e4d3c2b1a09f8e7d6c5b4a39281706f5e4d3c2b1a0f9e8d","importId":"imp-0001"}}
                     */
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
